### ISSUE TITLE
Invalid private key length with Key.FromBase58

### ISSUE THREAD

**Issue by newyellow** [trilitech/tezos-unity-sdk#16] opened 2023-03-04 16:14 UTC
I was working on a live-minting tool with Netezos & Unity. And since now the UnitySDK released, I'm porting my codes from Netezos to UnitySDK version of Netezos (the main different is the IEnumerator wrapper)

And I found an issue when I try to send transactions with private key, there's a "Invalid Private Key" warning in the UnitySDK version, and made my code fail. (I made a check that my length is 64 so the check failed)

It is in the Key.cs line 39 & 40
https://github.com/trilitech/tezos-unity-sdk/blob/main/Assets/Scripts/Netezos/Keys/Key.cs

I simply remove the length check, and it worked. The transaction also successfully sent to the blockchain. So I guess the check is unnecessary?

And here is my code:
`

        
        // This part will fail if the length check exists
        Key testKey = Key.FromBase58("my private key from Temple wallet");
        var address = testKey.Address;
        
        // RPC part
        TezosRpc rpc = new TezosRpc("https://mainnet.api.tez.ie");

        //var headBlockData = await rpc.Blocks.Head.Header.GetAsync();
        CoroutineWrapper<string> headCoroutine = new CoroutineWrapper<string>(rpc.Blocks.Head.Hash.GetAsync<string>());
        yield return headCoroutine;
        string headHash = headCoroutine.Result;

        CoroutineWrapper<int> counterCoroutine = new CoroutineWrapper<int>(rpc.Blocks.Head.Context.Contracts[address].Counter.GetAsync<int>());
        yield return counterCoroutine;
        int addressCounter = counterCoroutine.Result + 1;

        // call fxhash contract 'mint' entrypoint
        var operation = new TransactionContent
        {
            Source = testKey.Address,
            Destination = "KT1BJC12dG17CVvPKJ1VYaNnaT5mzfnUTwXv",
            Counter = addressCounter,
            Amount = 0,
            GasLimit = 46000,
            Fee = 6000,
            StorageLimit = 1000,
            Parameters = new Parameters
            {
                Entrypoint = "mint",
                Value = new MichelinePrim
                {
                    Prim = PrimType.Pair,
                    Args = new List<IMicheline>
                    {
                        new MichelineInt(14176),
                        new MichelinePrim
                        {
                            Prim = PrimType.Pair,
                            Args = new List<IMicheline>
                            {
                                new MichelinePrim{ Prim = PrimType.None },
                                new MichelinePrim{ Prim = PrimType.None }
                            }
                        }
                    }
                }
            }
        };

        CoroutineWrapper<byte[]> forgeCoroutine = new CoroutineWrapper<byte[]>(new LocalForge().ForgeOperationAsync(headHash, operation));
        yield return forgeCoroutine;
        var operationBytes = forgeCoroutine.Result;

        byte[] signature = testKey.SignOperation(operationBytes);

        CoroutineWrapper<dynamic> transactionCoroutine = new CoroutineWrapper<dynamic>(rpc.Inject.Operation.PostAsync(Combine(operationBytes, signature)));
        yield return transactionCoroutine;
        
        dynamic opResult = transactionCoroutine.Result;
`

**Comment by Groxan** [comment] 2023-03-04 18:12
There are multiple ed25519 implementations, which use different formats for storing long private keys (see [this](http://blog.mozilla.org/warner/files/2011/11/key-formats.png)). Therefore, when you pass 64 bytes, the library just can't know for sure of what format the private key you are passing. For example, if you remove that check and import a 64-bytes-key, exported with python implementation, it will work fine, because the first 32 bytes will contain a seed, but if you try to import a 64-bytes-key, exported with NaCl implementation, you will get a wrong key, because the first 32 bytes won't contain a seed. The wrong key will produce invalid signatures, etc., which is unacceptable, IMO.

So, if you have 64-bytes-key, you should know of what format it is and how to get a 32-bytes seed from it, to pass to Netezos, to avoid ambiguity and unpredictable behavior.

**Comment by m-kus** [comment] 2023-04-02 11:08
Hey! In version 1.1.0 the usage of Netezos library was refactored (more specifically, eliminated code duplication and updated latest version), can please try to reproduce on it?

**Comment by m-kus** [comment] 2023-04-26 17:17
Hi @newyellow! Are you still reproducing this issue?

**Comment by newyellow** [comment] 2023-04-27 05:24
Hi @m-kus, thank you for the reply. Since this v1.1 has a lot change from 1.0, I haven't really implement it yet. Cuz our exhibition is just about to start, I'm afraid that I might break the system, so didn't upgrade. I will try it this week or next. Thank you!

**Comment by fraidev** [comment] 2023-07-12 17:16
It seems that we don't have this length check, so I will be closing this issue for now.

**Closed by fraidev** 2023-07-12 17:16 UTC
Labels: bug, need more info
